# Generated by Django 6.1.1 on 2026-10-03 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_drive_file_id_material_source_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', True), ('file', ''), _connector='OR'), models.Q(('source_url__isnull', True), ('source_url', ''), _connector='OR'), _connector='XOR'), name='material_exactly_one_source'),
        ),
    ]
