# Generated by Django 6.1.1 on 2026-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_subject',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
